"""Read-operation registry enforcement.

Every outgoing Reddit request must match an *enabled* entry in
read_operations.json by exact HTTP method and normalized path. The registry is
generated by scripts/generate_registry.py and human-reviewed; this module only
enforces it. There is no way to register an operation at runtime.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from functools import lru_cache
from importlib import resources

_TEMPLATE_PARAM = re.compile(r"\{[a-z_]+\}")
# Conservative charset for a single path segment (Reddit IDs, enum-ish values).
_SEGMENT_RE = r"[A-Za-z0-9_\-.~]+"


class OperationDenied(PermissionError):
    """The requested upstream operation is not on the read allowlist."""


@dataclass(frozen=True)
class Operation:
    operation_id: str
    method: str
    path_template: str
    rate_group: str
    paginated: bool
    sensitivity: str
    _pattern: re.Pattern[str]

    def matches(self, method: str, path: str) -> bool:
        return method.upper() == self.method and bool(self._pattern.fullmatch(path))


def _compile(template: str) -> re.Pattern[str]:
    parts = _TEMPLATE_PARAM.split(template)
    pattern = _SEGMENT_RE.join(re.escape(p) for p in parts)
    return re.compile(pattern)


@lru_cache(maxsize=1)
def load_registry() -> tuple[Operation, ...]:
    raw = json.loads(
        resources.files("reddit_ads_mcp.policy")
        .joinpath("read_operations.json")
        .read_text()
    )
    ops = []
    for entry in raw["operations"]:
        if entry["classification"] != "enabled":
            continue
        method = entry["method"].upper()
        # Defense in depth: refuse to load a registry containing a write method
        # in an enabled entry, even if the generated file was tampered with.
        if method not in ("GET", "POST"):
            raise OperationDenied(
                f"registry contains enabled non-read method: {method} {entry['path']}"
            )
        ops.append(
            Operation(
                operation_id=entry["operation_id"],
                method=method,
                path_template=entry["path"],
                rate_group=entry.get("rate_group", "entity"),
                paginated=bool(entry.get("paginated")),
                sensitivity=entry.get("sensitivity", "standard"),
                _pattern=_compile(entry["path"]),
            )
        )
    return tuple(ops)


def normalize_path(path: str) -> str:
    """Normalize a candidate request path before matching.

    Rejects traversal and empty segments rather than resolving them.
    """
    if "\\" in path or "//" in path or not path.startswith("/"):
        raise OperationDenied(f"malformed request path: {path!r}")
    segments = path.split("/")
    if any(seg in (".", "..") for seg in segments):
        raise OperationDenied(f"path traversal rejected: {path!r}")
    return path.rstrip("/") or "/"


def authorize(method: str, path: str) -> Operation:
    """Return the matching enabled operation or raise OperationDenied."""
    normalized = normalize_path(path)
    for op in load_registry():
        if op.matches(method, normalized):
            return op
    raise OperationDenied(
        f"operation not on the read allowlist: {method.upper()} {normalized}"
    )
